openapi: 3.0.0
info:
  title: 'Filter API'
  version: '1.0.0'
paths:
  /filter:
    get:
      summary: 'Get all filters'
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              example:
                filters:
                  - id: 'string'
                    name: 'string'
                    image_url: 'string'
              schema:
                $ref: '#/components/schemas/Filter'
  /filter/{id}:
    get:
      summary: 'Get a filter'
      parameters:
        - in: path
          name: id
          required: true
          description: 'ID of filter'
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              example:
                id: 'string'
                name: 'string'
                image_url: 'string'
              schema:
                $ref: '#/components/schemas/Filter'
        '404':
          description: 'Could not find filter'
          content:
            application/json:
              example:
                error: true
                reason: 'string'
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: boolean
        reason:
          type: string

    Filter:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        image_url:
          type: string
          format: uri
