openapi: 3.0.0
info:
  title: 'Price Range API'
  version: '1.0.0'
paths:
  /price-range/{id}:
    get:
      summary: 'Get price range by ID'
      parameters:
        - in: path
          name: id
          required: true
          description: 'ID of price range'
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              example:
                id: 'string'
                range: 'string'
              schema:
                $ref: '#/components/schemas/PriceRange'
        '404':
          description: 'Could not find price range'
          content:
            application/json:
              example:
                error: true
                reason: 'Price range not found'
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    PriceRange:
      type: object
      properties:
        id:
          type: string
          format: uuid
        range:
          type: string
